### PR TITLE
Modifications for Digital Craftsmanship

### PR DESCRIPTION
**Pull request by Niekvan**
Dear Troy,

As I showed you last Friday in a glimpse, I would like to hereby share my code that automatically generates two parts of the insole. A heel and a toe part and creates two separate G code files, Ultimaker proof. I am struggling with the transformation from the picture to G code, as in G code only straight lines are generated and no curves. Do you know of a function or other conversion method?

Kind regards,

Niek van Sleeuwen

### CODE REVIEW

**Comment by troykyo** [comment]
Nick, 

You would have to interpolate the curve lines by adding points.

Some programs call this intermediate points with a natural algorithm added to adjust the points.  

The other option is Arcs in Gcode, but that is more of a masters level project.

I like what you are doing none the less.  Good work.
Troy

**Comment by Niekvan** [comment]
Hey Troy,

We are having trouble with the retraction, according to the code is fine and when we look at the back of the printer we see it retracting the material. Somehow it still keeps printing the moving lines. We even set the temperature to its lowest possible value to strike out the possibility of dripping because of the heat. Do you maybe have an idea how to solve this? Or should we pump up the retraction even more? It’s already a 100 in the processing code.
I added the G code file in the attachments.

Kind regards,

Niek
Van: Troy Nachtigall [mailto:notifications@github.com]
Verzonden: zondag 15 mei 2016 18:11
Aan: troykyo/SoleMakerSavingGcode SoleMakerSavingGcode@noreply.github.com
CC: Sleeuwen, N.C. van n.c.v.sleeuwen@student.tue.nl; Author author@noreply.github.com
Onderwerp: Re: [troykyo/SoleMakerSavingGcode] Modifications for Digital Craftsmanship (#1)

Nick,

You would have to interpolate the curve lines by adding points.

Some programs call this intermediate points with a natural algorithm added to adjust the points.

The other option is Arcs in Gcode, but that is more of a masters level project.

I like what you are doing none the less. Good work.
Troy

**Comment by troykyo** [comment]
Hi Niek, 

we never solved it.  In the end we instituted combing to solve the issue.

Troy

**Comment by Niekvan** [comment]
Stale

**Pull request closed without merging**
